---
# WAN Management Settings

mgmt_interface_vrf: default
mgmt_gateway: null

custom_structured_configuration_switchport_default:
  mode: "routed"

custom_structured_configuration_agents:
  - name: KernelFib
    environment_variables:
      - name: KERNELFIB_PROGRAM_ALL_ECMP
        value: "'true'"

cvp_instance_ips: ["apiserver.arista.io"]

custom_structured_configuration_daemon_terminattr:
  cvauth:
    token_file: "/tmp/cv-onboarding-token"
  disable_aaa: true

custom_structured_configuration_system:
  l1:
    unsupported_speed_action: "error"
    unsupported_error_correction_action: "error"

custom_structured_configuration_ip_name_servers:
  - ip_address: 8.8.4.4
    vrf: default
  - ip_address: 8.8.8.8
    vrf: default

ntp_settings:
  server_vrf: default
  servers:
    - name: time.google.com

custom_structured_configuration_management_ssh:
  client_alive:
    interval: 180

aaa_authorization:
  exec:
    default: local

banners:
  login: |
    ************************************************************************

      WARNING: This system is for the use of authorized clients only.
                Individuals using the computer network system without
                authorization, or in excess of their authorization, are
                subject to having all their activity on this computer
                network system monitored and recorded by system
                personnel.  To protect the computer network system from
                unauthorized use and to ensure the computer network systems
                is functioning properly, system administrators monitor this
                system.  Anyone using this computer network system
                expressly consents to such monitoring and is advised that
                if such monitoring reveals possible conduct of criminal
                activity, system personnel may provide the evidence of
                such activity to law enforcement officers.

                Access is restricted to authorized users only.
                Unauthorized access is a violation of state and federal,
                civil and criminal laws.
    **************************************************************************
    EOF

skipped_tests:
  - category: AvdTestHardware
    tests:
      - VerifyEnvironmentPower
      - VerifyEnvironmentCooling
      - VerifyTemperature
      - VerifyTransceiversManufacturers
