---
# WAN Pathfinder Nodes

# type: wan_rr

custom_structured_configuration_local_users:
  - name: admin
    role: network-admin
    privilege: 15
    sha512_password: "$6$cvwrJmkkXM.q.4SQ$6FmmB4NCwUGaOK6ixek8b.JiGy0DYp48lxBi9Z3275F3xHWlrnCWb0qGiQT.oly5FwohlEDe5L0MP59EF.RJ4."

wan_rr: # dynamic_key: node_type
  defaults:
    data_plane_cpu_allocation_max: 4
    loopback_ipv4_pool: 10.254.99.0/30
    vtep_loopback_ipv4_pool: 192.168.99.0/30
    filter:
      always_include_vrfs_in_tenants: [hawaiianairlines]
  nodes:
    - name: arista-pf1-ch-test
      id: 1
      # mgmt_ip: 10.90.245.41/24
      mgmt_ip: null
      structured_config:
        router_bgp:
          router_id: 192.168.99.1
          vrfs:
            - name: default
              router_id: 192.168.99.1
            - name: STATION
              router_id: 192.168.99.1
      l3_interfaces:
        - name: Ethernet1
          ip_address: 142.215.104.113/31
          wan_carrier: internet
          peer_ip: 142.215.104.112
          static_routes:
            - prefix: 0.0.0.0/0
    - name: arista-pf2-ch-test
      id: 2
      # mgmt_ip: 10.90.245.35/24
      mgmt_ip: null
      structured_config:
        router_bgp:
          router_id: 192.168.99.2
          vrfs:
            - name: default
              router_id: 192.168.99.2
            - name: STATION
              router_id: 192.168.99.2
      l3_interfaces:
        - name: Ethernet1
          ip_address: 142.215.104.115/31
          wan_carrier: internet
          peer_ip: 142.215.104.114
          static_routes:
            - prefix: 0.0.0.0/0
