---
# Edge nodes configuration

# type: wan_edge
# type: wan_router

custom_structured_configuration_local_users:
  - name: demo
    role: network-admin
    privilege: 15
    sha512_password: "$6$UisBHbh7j0nDNbP9$3PzI4Cqr9NK.j.8hJV5enMrMuKDm9UEkugTDY0L0ASY4uefBHeeKA.o9WijOvXzYYBiXrcx6uk6oCsurDLYvR1"


wan_router:  # dynamic_key: node_type
  defaults:
    id: 1
    loopback_ipv4_offset: -1
    cv_pathfinder_region: Global
    filter:
      always_include_vrfs_in_tenants: [hawaiianairlines]
  nodes:
    - name: Site-DRF-INET-SDWAN
      cv_pathfinder_site: Site-DRF
      # mgmt_ip: 10.90.245.94/24
      mgmt_ip: null
      loopback_ipv4_pool: 10.254.110.1/32
      vtep_loopback_ipv4_pool: 192.168.110.1/32
      l3_interfaces:
        - name: Ethernet1/2
          ip_address: 76.81.100.242/29
          wan_carrier: internet
          ipv4_acl_in: DRF-inet-inbound
          ipv4_acl_out: DRF-inet-outbound
          peer_ip: 76.81.100.241
          static_routes:
            - prefix: 0.0.0.0/0
          cv_pathfinder_internet_exit: 
            policies:
              - name: STATION-avt-defaultIEPolicy
      structured_config:
        router_bgp:
          router_id: 192.168.110.1
          vrfs:
            - name: STATION
              router_id: 192.168.110.1
        dhcp_servers:
          - disabled: false
            vrf: STATION
            subnets:
              - subnet: 10.100.110.0/24
                name: Site-DRF-INET-SDWAN-STATION-LAN
                default_gateway: 10.100.110.1
                dns_servers: [ 8.8.8.8, 8.8.4.4 ]
                ranges:
                  - start: 10.100.110.10
                    end: 10.100.110.235
                lease_time:
                  days: 1
                  hours: 0
                  minutes: 0
      raw_eos_cli: |
        ip access-list DRF-inet-inbound
          permit response traffic nat

ipv4_acls:
  - name: DRF-inet-inbound
    entries: # required
      - source: 74.202.112.0/24
        destination: any
        sequence: 10
        action: "permit"
        protocol: ip
      - source: 142.215.104.113
        destination: any
        sequence: 20
        action: "permit"
        protocol: ip
      - source: 142.215.104.115
        destination: any
        sequence: 30
        action: "permit"
        protocol: ip
      - source: 142.215.198.172
        destination: any
        sequence: 40
        action: "permit"
        protocol: ip
      - source: 142.215.58.13
        destination: any
        sequence: 50
        action: "permit"
        protocol: ip
      - source: any
        destination: any
        sequence: 60
        action: "permit"
        protocol: udp
        source_ports_match: "eq"
        source_ports:
          - "ntp" 
          - "isakmp"
          - "3478"
          - "non500-isakmp"
      - source: 162.210.128.0/22
        destination: any
        sequence: 70
        action: "permit"
        protocol: ip
      - source: 34.67.65.165
        destination: any
        sequence: 80
        action: "permit"
        protocol: ip
      - source: 35.192.157.156
        destination: any
        sequence: 90
        action: "permit"
        protocol: ip
      - source: 34.136.239.116
        destination: any
        sequence: 100
        action: "permit"
        protocol: ip
      - source: 34.30.62.197
        destination: any
        sequence: 110
        action: "permit"
        protocol: ip
      - source: 8.8.8.8
        destination: any
        sequence: 120
        action: "permit"
        protocol: ip
      - source: 8.8.4.4
        destination: any
        sequence: 130
        action: "permit"
        protocol: ip
      - source: 13.107.64.0/18
        destination: any
        sequence: 140
        action: "permit"
        protocol: udp
        destination_ports_match: "eq"
        destination_ports:
          - "3478"
          - "3479"
          - "3480"
          - "3481"
      - source: 52.112.0.0/14
        destination: any
        sequence: 150
        action: "permit"
        protocol: udp
        destination_ports_match: "eq"
        destination_ports:
          - "3478"
          - "3479"
          - "3480"
          - "3481"
      - source: 52.122.0.0/15
        destination: any
        sequence: 160
        action: "permit"
        protocol: udp
        destination_ports_match: "eq"
        destination_ports:
          - "3478"
          - "3479"
          - "3480"
          - "3481"
      - source: 13.107.64.0/18
        destination: any
        sequence: 170
        action: "permit"
        protocol: icmp
      - source: 52.112.0.0/14
        destination: any
        sequence: 180
        action: "permit"
        protocol: icmp
      - source: 52.122.0.0/15
        destination: any
        sequence: 190
        action: "permit"
        protocol: icmp
      - source: 52.238.119.141
        destination: any
        sequence: 200
        action: "permit"
        protocol: tcp
        destination_ports_match: "eq"
        destination_ports:
          - "www"
          - "https"
      - source: 52.244.160.207
        destination: any
        sequence: 210
        action: "permit"
        protocol: tcp
        destination_ports_match: "eq"
        destination_ports:
          - "www"
          - "https"
      - source: 13.107.64.0/18
        destination: any
        sequence: 220
        action: "permit"
        protocol: tcp
        destination_ports_match: "eq"
        destination_ports:
          - "www"
          - "https"
      - source: 52.112.0.0/14
        destination: any
        sequence: 230
        action: "permit"
        protocol: tcp
        destination_ports_match: "eq"
        destination_ports:
          - "www"
          - "https"
      - source: 52.122.0.0/15
        destination: any
        sequence: 240
        action: "permit"
        protocol: tcp
        destination_ports_match: "eq"
        destination_ports:
          - "www"
          - "https"
  - name: DRF-inet-outbound
    entries: # required
      - source: any
        destination: any
        sequence: 10
        action: "permit"
        protocol: ip
