---
# WAN Transit Nodes

# type: wan_transit
# type: wan_router

custom_structured_configuration_local_users:
  - name: admin
    role: network-admin
    privilege: 15
    sha512_password: "$6$cvwrJmkkXM.q.4SQ$6FmmB4NCwUGaOK6ixek8b.JiGy0DYp48lxBi9Z3275F3xHWlrnCWb0qGiQT.oly5FwohlEDe5L0MP59EF.RJ4."


wan_router:  # dynamic_key: node_type
  defaults:
    id: 1
    loopback_ipv4_offset: -1
    cv_pathfinder_region: Global
    cv_pathfinder_transit_mode: region
    filter:
      always_include_vrfs_in_tenants: [hawaiianairlines]
  nodes:
    - name: arista-r2-ch-test
      cv_pathfinder_site: Site-EQX-ASH
      # mgmt_ip: 10.90.245.92/24
      mgmt_ip: null
      loopback_ipv4_pool: 10.254.109.1/32
      vtep_loopback_ipv4_pool: 192.168.109.1/32
      structured_config:
        router_bgp:
          router_id: 192.168.109.1
          vrfs:
            - name: default
              router_id: 192.168.109.1
            - name: STATION
              router_id: 192.168.109.1
      l3_interfaces:
        - name: Ethernet1
          ip_address: 142.215.58.13/31
          wan_carrier: internet
          peer_ip: 142.215.58.12
          static_routes:
            - prefix: 0.0.0.0/0
          # NO Internet-Exit on Hub
          # cv_pathfinder_internet_exit: 
          #   policies:
          #     - name: STATION-avt-defaultIEPolicy
