---
# WAN Transit Nodes

# type: wan_transit
# type: wan_router

local_users:
  - name: neteng1
    role: network-admin
    privilege: 15
    sha512_password: "$1$X3t8pt2v$FWMtZOAEnRyW6B2VRxTQW/"

wan_router:  # dynamic_key: node_type
  defaults:
    id: 1
    loopback_ipv4_offset: -1
    cv_pathfinder_region: Global
    cv_pathfinder_transit_mode: region
    filter:
      always_include_vrfs_in_tenants: [hawaiianairlines]
  nodes:
    - name: arista-r1-ch-test
      cv_pathfinder_site: Site-EQX-SEA
      loopback_ipv4_pool: 10.254.108.1/32
      vtep_loopback_ipv4_pool: 192.168.108.1/32
      structured_config:
        router_bgp:
          router_id: 192.168.108.1
      # mgmt_ip: 10.90.245.93/24
      mgmt_ip: null
      l3_interfaces:
        - name: Ethernet1
          ip_address: dhcp
          wan_carrier: internet
          peer_ip: 142.215.198.169
          static_routes:
            - prefix: 0.0.0.0/0
          cv_pathfinder_internet_exit: 
            policies:
              - name: STATION-avt-defaultIEPolicy
